# Site settings
title: Morpho
tagline: Yet another Bluesky

description: > # this means to ignore newlines until "url:"
  国内完結型SNS「モルフォ」の運用予定地および運営フォーラムです。
url: "https://about.morpho.social" # the base hostname & protocol for your site, e.g. http://example.com
email: "hello@morpho.social"

timezone: Asia/Tokyo

did: "did:plc:fothnjbgdlnmwae7oklslwh7"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  footnote_backlink: "&#x21a9;&#xfe0e;"
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

assets:
  compression: true # true on JEKYLL_ENV=production
  gzip: true
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
  precompile: all
  raw_precompile: all

# Gem settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Date format settings
date_format: "%Y年%-m月%-d日"

# Collections settings
collections:
  posts:
    output: true
    permalink: /:collection/:path.html

paginate: 10
paginate_path: "/:collection/page:num/"

include:
  - .well-known

exclude:
  - Gemfile
  - README.md

# End
