# Site settings
title: 群青財団設立準備会
tagline: "Gunjo Foundation, PrepCom."

description: > # this means to ignore newlines until "url:"
  国内完結型SNS「モルフォ」の開発団体です。
url: "https://www.gunjo.org" # the base hostname & protocol for your site, e.g. http://example.com
email: "hello@gunjo.org"

timezone: Asia/Tokyo

light:
  bg: "#fff"
  text: "rgba(3,10,18,.81)"
  border: "#e5e7eb"

dark:
  bg: "rgba(3,10,18,.81)"
  text: "#fff"
  border: "#e5e7eb"

quiet: gunjo
did: "did:plc:fothnjbgdlnmwae7oklslwh7"
github: gunjo-org

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  footnote_backlink: "&#x21a9;&#xfe0e;"
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

assets:
  compression: true # true on JEKYLL_ENV=production
  gzip: true
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
  precompile: all
  raw_precompile: all

# Gem settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Date format settings
date_format: "%Y年%-m月%-d日"

include:
  - .well-known

exclude:
  - Gemfile
  - README.md

# End
